export const data = {
  rutinas: [
    {
      id: 1,
      title: "Despertar",
      description: "Despertar",
      reading: "Buenos días, ¿cómo amaneciste?",
      hasImg: true,
    },
    {
      id: 2,
      title: "Levantarse",
      description: "Levantarse",
      reading: "Es hora de levantarse y comenzar el día.",
      hasImg: true,
    },
    {
      id: 3,
      title: "Ir al baño",
      description: "Al despertar, es importante ir al baño.",
      reading: "Al despertar, es importante ir al baño.",
      hasImg: true,
    },
    {
      id: 4,
      title: "Lavarse los dientes",
      description: "Es importante lavarse los dientes después de despertar.",
      reading: "Es importante lavarse los dientes después de despertar.",
      hasImg: true,
    },
    {
      id: 5,
      title: "Vestirse",
      description: "Vestirse adecuadamente después de despertar.",
      reading: "Es importante vestirse adecuadamente después de despertar.",
      hasImg: true,
    },
    {
      id: 6,
      title: "Desayunar",
      description: "Es importante desayunar para comenzar el día con energía.",
      reading: "Es importante desayunar para comenzar el día con energía.",
      hasImg: true,
    },
    {
      id: 7,
      title: "ir a la escuela",
      description: "Es importante ir al colegio para aprender.",
      reading: "Es importante ir al colegio para aprender.",
      hasImg: true,
    },
    {
      id: 8,
      title: "Ir a clases",
      description: "Es importante ir a clases para aprender.",
      reading: "Es importante ir a clases para aprender.",
      hasImg: true,
    },
    {
      id: 9,
      title: "Estudiar",
      description: "Es hora de estudiar y aprender.",
      reading: "¡Diviértete estudiando!",
      hasImg: true,
    },
    {
      id: 10,
      title: "Practicar deportes",
      description: "Es hora de practicar deporte y divertirse.",
      reading: "¡Diviértete practicando deporte!",
      hasImg: true,
    },
    {
      id: 11,
      title: "Almorzar",
      description: "Es hora de almorzar y recargar energías.",
      reading: "Hora de almorzar y recargar energías.",
      hasImg: true,
    },
    {
      id: 12,
      title: "Volver a casa",
      description: "Es hora de volver a casa.",
      reading: "Es hora de volver a casa",
      hasImg: true,
    },
    {
      id: 13,
      title: "Merendar",
      description: "Es hora de merendar y relajarse.",
      reading: "Es hora de merendar y relajarse.",
      hasImg: true,
    },
    {
      id: 14,
      title: "Hacer los deberes",
      description: "Es hora de hacer los deberes.",
      reading: "Es hora de hacer los deberes",
      hasImg: true,
    },

    {
      id: 15,
      title: "Jugar a la consola",
      description: "Es hora de jugar y divertirse.",
      reading: "¡Diviértete jugando!",
      hasImg: true,
    },
    {
      id: 16,
      title: "Navegar en las redes",
      description: "Es hora de navegar en las redes.",
      reading: "Es hora de navegar en las redes.",
      hasImg: true,
    },
    {
      id: 17,
      title: "Ver televisión",
      description: "Es hora de ver televisión y relajarse.",
      reading: "Es hora de ver televisión y relajarse.",
      hasImg: true,
    },
    {
      id: 18,
      title: "Pasear al perro",
      description: "Es hora de pasear al perro.",
      reading: "Es hora de pasear al perro.",
      hasImg: true,
    },
    {
      id: 19,
      title: "Ayudar a los padres",
      description: "Es hora de ayudar a los padres en casa.",
      reading: "Es hora de ayudar a los padres en casa.",
      hasImg: true,
    },
    {
      id: 20,
      title: "Poner la mesa",
      description: "Es hora de poner la mesa.",
      reading: "Es hora de poner la mesa.",
      hasImg: true,
    },
    {
      id: 21,
      title: "Cenar",
      description: "Es hora de cenar.",
      reading: "Es hora de cenar.",
      hasImg: true,
    },
    {
      id: 22,
      title: "Ducharse",
      description: "Es hora de ducharse.",
      reading: "¡A bañarse!",
      hasImg: true,
    },
    {
      id: 23,
      title: "leer",
      description: "Es hora de leer.",
      reading: "Vamos a leer un libro",
      hasImg: true,
    },
    {
      id: 12,
      title: "Acostarse",
      description: "Es hora de acostarse.",
      reading: "A dormir",
      hasImg: true,
    },
  ],
  acciones: [
    // NECESIDADES BÁSICAS
    {
      id: 1,
      title: "Agua",
      description: "Pedir agua para beber.",
      reading: "Quiero agua.",
      category: "necesidades",
      hasImg: false,
    },
    {
      id: 2,
      title: "Comer",
      description: "Pedir comida.",
      reading: "Tengo hambre.",
      category: "necesidades",
      hasImg: false,
    },
    {
      id: 3,
      title: "Baño",
      description: "Pedir ir al baño.",
      reading: "Necesito ir al baño.",
      category: "necesidades",
      hasImg: false,
    },
    {
      id: 4,
      title: "Dormir",
      description: "Pedir ir a dormir.",
      reading: "Quiero dormir.",
      category: "necesidades",
      hasImg: false,
    },

    // ESTADOS FÍSICOS
    {
      id: 5,
      title: "Cansado",
      description: "Decir que está cansado.",
      reading: "Estoy cansado.",
      category: "estados",
      hasImg: false,
    },
    {
      id: 6,
      title: "Sed",
      description: "Decir que tiene sed.",
      reading: "Tengo sed.",
      category: "estados",
      hasImg: false,
    },
    {
      id: 7,
      title: "Frío",
      description: "Decir que tiene frío.",
      reading: "Tengo frío.",
      category: "estados",
      hasImg: false,
    },
    {
      id: 8,
      title: "Calor",
      description: "Decir que tiene calor.",
      reading: "Tengo calor.",
      category: "estados",
      hasImg: false,
    },
    {
      id: 9,
      title: "Dolor",
      description: "Decir que le duele algo.",
      reading: "Me duele.",
      category: "estados",
      hasImg: false,
    },

    // ACTIVIDADES
    {
      id: 10,
      title: "Jugar",
      description: "Pedir jugar.",
      reading: "Quiero jugar.",
      category: "actividades",
      hasImg: false,
    },
    {
      id: 11,
      title: "Plaza",
      description: "Pedir ir a la plaza.",
      reading: "Vamos a la plaza.",
      category: "actividades",
      hasImg: false,
    },
    {
      id: 12,
      title: "Música",
      description: "Pedir escuchar música.",
      reading: "Pon música.",
      category: "actividades",
      hasImg: false,
    },

    // PREFERENCIAS
    {
      id: 13,
      title: "Sí",
      description: "Decir que sí quiere algo.",
      reading: "Sí.",
      category: "preferencias",
      hasImg: false,
    },
    {
      id: 14,
      title: "No",
      description: "Decir que no quiere algo.",
      reading: "No.",
      category: "preferencias",
      hasImg: false,
    },
    {
      id: 15,
      title: "Más",
      description: "Pedir más de algo.",
      reading: "Quiero más.",
      category: "preferencias",
      hasImg: false,
    },
    {
      id: 16,
      title: "Basta",
      description: "Decir que ya no quiere más.",
      reading: "Ya basta.",
      category: "preferencias",
      hasImg: false,
    },

    // SOCIALES
    {
      id: 17,
      title: "Gracias",
      description: "Decir gracias.",
      reading: "Gracias.",
      category: "sociales",
      hasImg: false,
    },
    {
      id: 18,
      title: "Te quiero",
      description: "Decir te quiero.",
      reading: "Te quiero.",
      category: "sociales",
      hasImg: false,
    },
    {
      id: 19,
      title: "Lo siento",
      description: "Pedir disculpas.",
      reading: "Lo siento.",
      category: "sociales",
      hasImg: false,
    },
    {
      id: 20,
      title: "Hola",
      description: "Saludar.",
      reading: "Hola.",
      category: "sociales",
      hasImg: false,
    },

    // EMERGENCIAS
    {
      id: 21,
      title: "Ayuda",
      description: "Pedir ayuda urgente.",
      reading: "¡Ayuda!",
      category: "emergencias",
      hasImg: false,
    },
    {
      id: 22,
      title: "Alto",
      description: "Decir que pare.",
      reading: "¡Alto!",
      category: "emergencias",
      hasImg: false,
    },
  ],
  canciones: {
    "bichi-kids": [
      {
        id: 1,
        title: "De Vuelta A La Escuela",
        description: "De Vuelta A La Escuela",
        reading: "De Vuelta A La Escuela",
        img: "bichi-kids.webp",
        video:
          "/assets/videos/webm/canciones-de-vuelta-a-la-escuela-asi-vamos-a-la-escuela-canciones-infantiles-bichikids.webm",
      },
      {
        id: 2,
        title: "Ki Ki Y Las Formas GeoméTricas",
        description: "Ki Ki Y Las Formas GeoméTricas",
        reading: "Ki Ki Y Las Formas GeoméTricas",
        img: "bichi-kids.webp",
        video:
          "/assets/videos/webm/canciones-ki-ki-y-las-formas-geometricas-vamos-a-ordenar-jugando-bichikids.webm",
      },
      {
        id: 3,
        title: "La Arañita Na Na",
        description: "La Arañita Na Na",
        reading: "La Arañita Na Na",
        img: "bichi-kids.webp",
        video:
          "/assets/videos/webm/canciones-la-aranita-na-na-canciones-infantiles-10-minutos-bichikids.webm",
      },
      {
        id: 4,
        title: "La La La Mosca",
        description: "La La La Mosca",
        reading: "La La La Mosca",
        img: "bichi-kids.webp",
        video:
          "/assets/videos/webm/canciones-la-la-la-mosca-cancion-infantil-bichikids.webm",
      },
      {
        id: 5,
        title: "Las Vocales Aprendizaje Para Niños",
        description: "Las Vocales Aprendizaje Para Niños",
        reading: "Las Vocales Aprendizaje Para Niños",
        img: "bichi-kids.webp",
        video:
          "/assets/videos/webm/canciones-las-vocales-aprendizaje-para-ninos-cancion-original-de-bichikids-canciones-infantiles.webm",
      },
      {
        id: 6,
        title: "Los Bichitos Bailan",
        description: "Los Bichitos Bailan",
        reading: "Los Bichitos Bailan",
        img: "bichi-kids.webp",
        video:
          "/assets/videos/webm/canciones-los-bichitos-bailan-cancion-infantil-bichikids.webm",
      },
      {
        id: 7,
        title: "Si Usted Tiene Muchas Ganas De Aplaudir",
        description: "Si Usted Tiene Muchas Ganas De Aplaudir",
        reading: "Si Usted Tiene Muchas Ganas De Aplaudir",
        img: "bichi-kids.webp",
        video:
          "/assets/videos/webm/canciones-si-usted-tiene-muchas-ganas-de-aplaudir-bichikids.webm",
      },
      {
        id: 8,
        title: "Aburrido Puede Ser Muy Divertido",
        description: "Aburrido Puede Ser Muy Divertido",
        reading: "Aburrido Puede Ser Muy Divertido",
        img: "bichi-kids.webp",
        video:
          "/assets/videos/webm/canciones-aburrido-puede-ser-muy-divertido-cancion-con-historia-bichikids.webm",
      },
      {
        id: 9,
        title: "Cómo Te Llamas Buenos Amigos Vamos A Ser",
        description: "Cómo Te Llamas Buenos Amigos Vamos A Ser",
        reading: "Cómo Te Llamas Buenos Amigos Vamos A Ser",
        img: "bichi-kids.webp",
        video:
          "/assets/videos/webm/canciones-como-te-llamas-buenos-amigos-vamos-a-ser-para-bebes-cancion-infantil-bichikids.webm",
      },
    ],
    "toy-cantando": [
      {
        id: 1,
        title: "Canción De La Vaca Lola Remix",
        description: "Canción De La Vaca Lola Remix",
        reading: null,
        img: "toy-cantando.webp",
        video:
          "/assets/videos/webm/canciones-cancion-de-la-vaca-lola-remix-canciones-infantiles-toy-cantando.webm",
      },
      {
        id: 2,
        title: "Canción De La Vaca Lola",
        description: "Canción De La Vaca Lola",
        reading: null,
        img: "toy-cantando.webp",
        video:
          "/assets/videos/webm/canciones-cancion-de-la-vaca-lola-canciones-infantiles-toy-cantando.webm",
      },
      {
        id: 3,
        title: "Chuchuwa",
        description: "Chuchuwa",
        reading: null,
        img: "toy-cantando.webp",
        video:
          "/assets/videos/webm/canciones-chuchuwa-canciones-infantiles-toy-cantando.webm",
      },
      {
        id: 4,
        title: "El Gusano Ciempiés",
        description: "El Gusano Ciempiés",
        reading: null,
        img: "toy-cantando.webp",
        video:
          "/assets/videos/webm/canciones-el-gusano-ciempies-canciones-infantiles-toy-cantando.webm",
      },
      {
        id: 5,
        title: "El Sapo No Se Lava El Pie",
        description: "El Sapo No Se Lava El Pie",
        reading: null,
        img: "toy-cantando.webp",
        video:
          "/assets/videos/webm/canciones-el-sapo-no-se-lava-el-pie-aprende-las-vocales-con-lulu-y-los-patiamigos-toy-cantando.webm",
      },
      {
        id: 6,
        title: "En Un Bosque De La China",
        description: "En Un Bosque De La China",
        reading: null,
        img: "toy-cantando.webp",
        video:
          "/assets/videos/webm/canciones-en-un-bosque-de-la-china-canciones-infantiles-toy-cantando.webm",
      },
      {
        id: 7,
        title: "La Risa De Las Vocales",
        description: "La Risa De Las Vocales",
        reading: null,
        img: "toy-cantando.webp",
        video:
          "/assets/videos/webm/canciones-la-risa-de-las-vocales-canciones-infantiles-toy-cantando.webm",
      },
      {
        id: 8,
        title: "La Vaca Lola",
        description: "La Vaca Lola",
        reading: null,
        img: "toy-cantando.webp",
        video:
          "/assets/videos/webm/canciones-la-vaca-lola-canciones-infantiles-toy-cantando.webm",
      },
      {
        id: 9,
        title: "La Hormiguita Con La Vaca Lola",
        description: "La Hormiguita Con La Vaca Lola",
        reading: null,
        img: "toy-cantando.webp",
        video:
          "/assets/videos/webm/canciones-la-hormiguita-con-la-vaca-lola-musica-infantil-toy-cantando.webm",
      },
      {
        id: 10,
        title: "La Ronda De Las Vocales",
        description: "La Ronda De Las Vocales",
        reading: null,
        img: "toy-cantando.webp",
        video:
          "/assets/videos/webm/canciones-la-ronda-de-las-vocales-canciones-infantiles-toy-cantando.webm",
      },
      {
        id: 11,
        title: "La Vaca Lola Baila A Lo Loco",
        description: "La Vaca Lola Baila A Lo Loco",
        reading: null,
        img: "toy-cantando.webp",
        video:
          "/assets/videos/webm/canciones-la-vaca-lola-baila-a-lo-loco-cancion-infantil-para-bailar-y-reir-toy-cantando.webm",
      },
      {
        id: 12,
        title: "La Vaca Lola Y El Tractor De La Granja",
        description: "La Vaca Lola Y El Tractor De La Granja",
        reading: null,
        img: "toy-cantando.webp",
        video:
          "/assets/videos/webm/canciones-la-vaca-lola-y-el-tractor-de-la-granja-canciones-infantiles-toy-cantando.webm",
      },
      {
        id: 13,
        title: "Pin Pon Es Un Muioeco",
        description: "Pin Pon Es Un Muioeco",
        reading: null,
        img: "toy-cantando.webp",
        video:
          "/assets/videos/webm/canciones-pin-pon-es-un-muneco-canciones-infantiles-toy-cantando.webm",
      },
    ],
  },
  juegos: {
    abcencastra: {
      id: 1,
      title: "ABCencastra",
      description: "Juego de encastre.",
      reading: "¡Vamos a encastrar!",
      hasImg: true,
      letters: Array.from({ length: 26 }, (_, i) =>
        String.fromCharCode(65 + i)
      ),
    },
    "pizarra-magica": {
      id: 2,
      title: "Pizarra Mágica",
      description: "A dibujar.",
      reading: "¡Es hora de dibujar!",
      hasImg: true,
    },
    puzzle: {
      id: 3,
      title: "Puzzle",
      description: "Puzzle",
      reading: "No puede ser, ¡que dificil!",
      hasImg: true,
    },
  },
};
