export const RAW_PUNCTUATION: Record<string, Record<string, string>> = {
  es: {
    'punto y aparte': '.\n\n',
    'punto y aparte,': '.\n\n',
    'punto y seguido': '. ',
    'punto y seguido,': '. ',
    'punto seguido': '. ',
    'punto final': '.\n\n',
    'punto y coma': '; ',
    'punto y,': '; ',
    'punto y coma,': '; ',
    'dos puntos': ': ',
    'dos puntos,': ': ',
    'punto': '. ',
    'punto,': '. ',
    'coma': ', ',
    'coma,': ', ',
    'nueva línea': '\n',
    'nueva linea': '\n',
    'salto de línea': '\n',
    'salto de linea': '\n',
    'salto linea': '\n',
    'nuevo renglón': '\n',
    'nuevo renglon': '\n',
    'nuevo párrafo': '\n\n',
    'nuevo parrafo': '\n\n',
    'tabulación': '__TAB__',
    'tab': '__TAB__',
    'signo de interrogación abierto': '¿',
    'abrir interrogación': '¿',
    'abre interrogación': '¿',
    'signo de pregunta abierto': '¿',
    'abrir pregunta': '¿',
    'abre pregunta': '¿',
    'signo de interrogación cerrado': '?',
    'cerrar interrogación': '?',
    'cierra interrogación': '?',
    'signo de pregunta cerrado': '?',
    'cerrar pregunta': '?',
    'cierra pregunta': '?',
    'signo de interrogación': '?',
    'signo de pregunta': '?',
    'signo de exclamación abierto': '¡',
    'abrir exclamación': '¡',
    'abre exclamación': '¡',
    'signo de admiración abierto': '¡',
    'abrir admiración': '¡',
    'abre admiración': '¡',
    'signo de exclamación cerrado': '!',
    'cerrar exclamación': '!',
    'cierra exclamación': '!',
    'signo de admiración cerrado': '!',
    'cerrar admiración': '!',
    'cierra admiración': '!',
    'signo de exclamación': '!',
    'signo de admiración': '!',
    'abrir paréntesis': '(',
    'paréntesis abierto': '(',
    'cerrar paréntesis': ')',
    'paréntesis cerrado': ')',
    'abrir comillas': '"',
    'comillas abiertas': '"',
    'cerrar comillas': '"',
    'comillas cerradas': '"',
    'guión bajo': '_',
    'guion bajo': '_',
    'guión': '-',
    'guion': '-',
    'barra baja': '_',
    'barra diagonal': '/',
    'diagonal': '/',
    'arroba': '@',
    'asterisco': '*',
    'porcentaje': '%',
    'signo número': '#',
    'signo de número': '#',
    'símbolo número': '#',
    'símbolo de número': '#',
    'numeral': '#',
    'hashtag': '#',
    'signo más': '+',
    'signo de más': '+',
    'símbolo más': '+',
    'símbolo de más': '+',
    'signo suma': '+',
    'signo menos': '-',
    'signo de menos': '-',
    'símbolo menos': '-',
    'símbolo de menos': '-',
    'signo resta': '-',
    'signo igual': '=',
    'signo de igual': '=',
    'símbolo igual': '=',
    'símbolo de igual': '=',
    'punto net': '.net',
    'punto com': '.com',
  },
  en: {
    'new paragraph': '\n\n',
    'new line': '\n',
    'next line': '\n',
    'period': '. ',
    'full stop': '. ',
    'dot': '. ',
    'comma': ', ',
    'colon': ': ',
    'semicolon': '; ',
    'tab': '__TAB__',
    'question mark': '?',
    'exclamation mark': '!',
    'exclamation point': '!',
    'open parenthesis': '(',
    'left parenthesis': '(',
    'close parenthesis': ')',
    'right parenthesis': ')',
    'open quote': '"',
    'open quotes': '"',
    'double quote': '"',
    'close quote': '"',
    'close quotes': '"',
    'close double quotes': '"',
    'dash': '-',
    'hyphen': '-',
    'underscore': '_',
    'forward slash': '/',
    'slash': '/',
    'at sign': '@',
    'dot com': '.com',
    'percent sign': '%',
    'percent': '%',
    'pound key': '#',
    'hashtag': '#',
    'hash': '#',
    'asterisk': '*',
    'plus sign': '+',
    'minus sign': '-',
    'equals sign': '=',
    'equal sign': '=',
    'number sign': '#',
    'hash sign': '#',
  },
  fr: {
    'point à la ligne': '.\n\n',
    'nouveau paragraphe': '\n\n',
    'nouvelle ligne': '\n',
    'point final': '. ',
    'point': '. ',
    'virgule': ', ',
    'deux points': ': ',
    'point-virgule': '; ',
    'point virgule': '; ',
    'tabulation': '__TAB__',
    'tab': '__TAB__',
    "point d'interrogation": '?',
    "point d'exclamation": '!',
    'ouvrir la parenthèse': '(',
    'parenthèse ouverte': '(',
    'fermer la parenthèse': ')',
    'parenthèse fermée': ')',
    'ouvrir les guillemets': '"',
    'guillemets ouverts': '"',
    'fermer les guillemets': '"',
    'guillemets fermés': '"',
    'tiret du milieu': '-',
    'tiret': '-',
    'tiret du bas': '_',
    'arobase': '@',
    'barre oblique': '/',
    'slash': '/',
    'pourcentage': '%',
    'dièse': '#',
    'astérisque': '*',
    'signe plus': '+',
    'signe moins': '-',
    'signe égal': '=',
    'signe egal': '=',
  },
  pt: {
    'ponto parágrafo': '.\n\n',
    'novo parágrafo': '\n\n',
    'nova linha': '\n',
    'ponto final': '. ',
    'ponto': '. ',
    'vírgula': ', ',
    'dois pontos': ': ',
    'ponto e vírgula': '; ',
    'tabulação': '__TAB__',
    'tab': '__TAB__',
    'ponto de interrogação': '?',
    'ponto de exclamação': '!',
    'abrir parêntese': '(',
    'parêntese aberto': '(',
    'fechar parêntese': ')',
    'parêntese fechado': ')',
    'abrir aspas': '"',
    'aspas abertas': '"',
    'fechar aspas': '"',
    'aspas fechadas': '"',
    'travessão': '-',
    'hífen': '-',
    'underline': '_',
    'subtraço': '_',
    'barra': '/',
    'arroba': '@',
    'porcentagem': '%',
    'jogo da velha': '#',
    'hashtag': '#',
    'asterisco': '*',
    'sinal de mais': '+',
    'sinal mais': '+',
    'sinal de menos': '-',
    'sinal menos': '-',
    'sinal de igual': '=',
    'sinal igual': '=',
  },
  it: {
    'punto a capo': '.\n\n',
    'nuovo paragrafo': '\n\n',
    'nuova riga': '\n',
    'punto': '. ',
    'virgola': ', ',
    'due punti': ': ',
    'punto e virgola': '; ',
    'tabulazione': '__TAB__',
    'tab': '__TAB__',
    'punto interrogativo': '?',
    'punto esclamativo': '!',
    'apri parentesi': '(',
    'parentesi aperta': '(',
    'chiudi parentesi': ')',
    'parentesi chiusa': ')',
    'apri virgolette': '"',
    'virgolette aperte': '"',
    'chiudi virgolette': '"',
    'virgolette chiuse': '"',
    'trattino': '-',
    'trattino basso': '_',
    'underscore': '_',
    'barra': '/',
    'slash': '/',
    'chiocciola': '@',
    'percento': '%',
    'cancelletto': '#',
    'asterisco': '*',
    'segno più': '+',
    'segno piu': '+',
    'segno meno': '-',
    'segno uguale': '=',
  },
  de: {
    'neuer absatz': '.\n\n',
    'neue zeile': '\n',
    'punkt': '. ',
    'komma': ', ',
    'doppelpunkt': ': ',
    'semikolon': '; ',
    'strichpunkt': '; ',
    'tabulator': '__TAB__',
    'tab': '__TAB__',
    'fragezeichen': '?',
    'ausrufezeichen': '!',
    'klammer auf': '(',
    'offene klammer': '(',
    'klammer zu': ')',
    'geschlossene klammer': ')',
    'anführungszeichen öffnen': '"',
    'anführungszeichen oben': '"',
    'anführungszeichen schließen': '"',
    'anführungszeichen unten': '"',
    'bindestrich': '-',
    'unterstrich': '_',
    'schrägstrich': '/',
    'at-zeichen': '@',
    'at': '@',
    'prozent': '%',
    'raute': '#',
    'asterisk': '*',
    'sternchen': '*',
    'pluszeichen': '+',
    'minuszeichen': '-',
    'gleichheitszeichen': '=',
  },
  ja: {
    '新しい段落': '\n\n',
    'あたらしいだんらく': '\n\n',
    '改行': '\n',
    'かいぎょう': '\n',
    'てん': '。',
    '句点': '。',
    'まる': '。',
    '読点': '、',
    'とうてん': '、',
    'てんてん': '、',
    'タブ': '__TAB__',
    '疑問符': '？',
    'ぎもんふ': '？',
    'はてな': '？',
    '感嘆符': '！',
    'かんたんふ': '！',
    'びっくりまーく': '！',
    '括弧開く': '（',
    'かっこひらく': '（',
    '括弧閉じる': '）',
    'かっことじる': '）',
    '引用符': '「',
    '閉じ引用符': '」',
    'とじいんようふ': '」',
    'ダッシュ': '—',
    'スラッシュ': '/',
    'アットマーク': '@',
    'パーセント': '%',
    'シャープ': '#',
    'アスタリスク': '*',
    'プラス記号': '+',
    'マイナス記号': '-',
    'イコール記号': '＝',
  }
};

export const RAW_FORMATS: Record<string, Array<{ phrases: string[]; command: any }>> = {
  es: [
    { phrases: ['iniciar negrita', 'activar negrita', 'empezar negrita'], command: { type: 'bold', value: true } },
    { phrases: ['finalizar negrita', 'terminar negrita', 'desactivar negrita'], command: { type: 'bold', value: false } },
    { phrases: ['iniciar cursiva', 'activar cursiva', 'empezar cursiva'], command: { type: 'italic', value: true } },
    { phrases: ['finalizar cursiva', 'terminar cursiva', 'desactivar cursiva'], command: { type: 'italic', value: false } },
    { phrases: ['iniciar subrayado', 'activar subrayado', 'empezar subrayado'], command: { type: 'underline', value: true } },
    { phrases: ['finalizar subrayado', 'terminar subrayado', 'desactivar subrayado'], command: { type: 'underline', value: false } },
    { phrases: ['aumentar sangría', 'agregar sangría', 'más sangría'], command: { type: 'indent' } },
    { phrases: ['disminuir sangría', 'quitar sangría', 'menos sangría'], command: { type: 'outdent' } },
    { phrases: ['iniciar título 4', 'insertar título 4'], command: { type: 'formatBlock', value: 'h4' } },
    { phrases: ['finalizar título 4', 'terminar título 4'], command: { type: 'formatBlock', value: 'p' } },
    { phrases: ['iniciar título 3', 'insertar título 3'], command: { type: 'formatBlock', value: 'h3' } },
    { phrases: ['finalizar título 3', 'terminar título 3'], command: { type: 'formatBlock', value: 'p' } },
    { phrases: ['iniciar título 2', 'insertar título 2'], command: { type: 'formatBlock', value: 'h2' } },
    { phrases: ['finalizar título 2', 'terminar título 2'], command: { type: 'formatBlock', value: 'p' } },
    { phrases: ['iniciar título', 'insertar título', 'iniciar título 1', 'insertar título 1'], command: { type: 'formatBlock', value: 'h1' } },
    { phrases: ['finalizar título', 'terminar título', 'finalizar título 1', 'terminar título 1'], command: { type: 'formatBlock', value: 'p' } },
    { phrases: ['cambiar tamaño de fuente chico', 'tamaño de fuente chico', 'fuente chica', 'fuente pequeña'], command: { type: 'fontSize', value: 2 } },
    { phrases: ['cambiar tamaño de fuente normal', 'tamaño de fuente normal', 'fuente normal', 'fuente mediana'], command: { type: 'fontSize', value: 3 } },
    { phrases: ['cambiar tamaño de fuente grande', 'tamaño de fuente grande', 'fuente grande'], command: { type: 'fontSize', value: 4 } },
    { phrases: ['cambiar tamaño de fuente muy grande', 'tamaño de fuente muy grande'], command: { type: 'fontSize', value: 5 } },
    { phrases: ['cambiar tamaño de fuente gigante', 'tamaño de fuente gigante'], command: { type: 'fontSize', value: 6 } },
    { phrases: ['alinear texto a la izquierda', 'alinear texto izquierdo'], command: { type: 'justifyLeft' } },
    { phrases: ['alinear texto al centro', 'alinear texto centrado'], command: { type: 'justifyCenter' } },
    { phrases: ['alinear texto a la derecha', 'alinear texto derecho'], command: { type: 'justifyRight' } },
  ],
  en: [
    { phrases: ['start bold', 'enable bold', 'turn on bold'], command: { type: 'bold', value: true } },
    { phrases: ['stop bold', 'disable bold', 'turn off bold', 'end bold'], command: { type: 'bold', value: false } },
    { phrases: ['start italic', 'enable italic', 'turn on italic'], command: { type: 'italic', value: true } },
    { phrases: ['stop italic', 'disable italic', 'turn off italic', 'end italic'], command: { type: 'italic', value: false } },
    { phrases: ['start underline', 'enable underline', 'turn on underline'], command: { type: 'underline', value: true } },
    { phrases: ['stop underline', 'disable underline', 'turn off underline', 'end underline'], command: { type: 'underline', value: false } },
    { phrases: ['increase indent', 'add indent'], command: { type: 'indent' } },
    { phrases: ['decrease indent', 'remove indent'], command: { type: 'outdent' } },
    { phrases: ['insert title 4', 'start title 4'], command: { type: 'formatBlock', value: 'h4' } },
    { phrases: ['end title 4', 'stop title 4', 'finish title 4'], command: { type: 'formatBlock', value: 'p' } },
    { phrases: ['insert title 3', 'start title 3'], command: { type: 'formatBlock', value: 'h3' } },
    { phrases: ['end title 3', 'stop title 3', 'finish title 3'], command: { type: 'formatBlock', value: 'p' } },
    { phrases: ['insert title 2', 'start title 2'], command: { type: 'formatBlock', value: 'h2' } },
    { phrases: ['end title 2', 'stop title 2', 'finish title 2'], command: { type: 'formatBlock', value: 'p' } },
    { phrases: ['insert title 1', 'start title 1', 'insert title', 'start title'], command: { type: 'formatBlock', value: 'h1' } },
    { phrases: ['end title 1', 'stop title 1', 'finish title 1', 'end title', 'stop title', 'finish title'], command: { type: 'formatBlock', value: 'p' } },
    { phrases: ['change font size small', 'change font size tiny', 'font size small', 'font size tiny'], command: { type: 'fontSize', value: 2 } },
    { phrases: ['change font size normal', 'change font size medium', 'font size normal', 'font size medium'], command: { type: 'fontSize', value: 3 } },
    { phrases: ['change font size large', 'change font size big', 'font size large', 'font size big'], command: { type: 'fontSize', value: 4 } },
    { phrases: ['change font size very large', 'font size very large'], command: { type: 'fontSize', value: 5 } },
    { phrases: ['change font size huge', 'change font size giant', 'font size huge', 'font size giant'], command: { type: 'fontSize', value: 6 } },
    { phrases: ['align text left'], command: { type: 'justifyLeft' } },
    { phrases: ['align text center'], command: { type: 'justifyCenter' } },
    { phrases: ['align text right'], command: { type: 'justifyRight' } },
  ],
  fr: [
    { phrases: ['activer gras', 'commencer gras'], command: { type: 'bold', value: true } },
    { phrases: ['désactiver gras', 'fin gras'], command: { type: 'bold', value: false } },
    { phrases: ['activer italique', 'commencer italique'], command: { type: 'italic', value: true } },
    { phrases: ['désactiver italique', 'fin italique'], command: { type: 'italic', value: false } },
    { phrases: ['activer souligné', 'commencer souligné'], command: { type: 'underline', value: true } },
    { phrases: ['désactiver souligné', 'fin souligné'], command: { type: 'underline', value: false } },
    { phrases: ['augmenter retrait', 'ajouter retrait'], command: { type: 'indent' } },
    { phrases: ['diminuer retrait', 'enlever retrait'], command: { type: 'outdent' } },
    { phrases: ['insérer titre 4', 'commencer titre 4'], command: { type: 'formatBlock', value: 'h4' } },
    { phrases: ['fin titre 4', 'terminer titre 4'], command: { type: 'formatBlock', value: 'p' } },
    { phrases: ['insérer titre 3', 'commencer titre 3'], command: { type: 'formatBlock', value: 'h3' } },
    { phrases: ['fin titre 3', 'terminer titre 3'], command: { type: 'formatBlock', value: 'p' } },
    { phrases: ['insérer titre 2', 'commencer titre 2'], command: { type: 'formatBlock', value: 'h2' } },
    { phrases: ['fin titre 2', 'terminer titre 2'], command: { type: 'formatBlock', value: 'p' } },
    { phrases: ['insérer titre', 'commencer titre', 'insérer titre 1', 'commencer titre 1'], command: { type: 'formatBlock', value: 'h1' } },
    { phrases: ['fin titre', 'terminer titre', 'fin titre 1', 'terminer titre 1'], command: { type: 'formatBlock', value: 'p' } },
    { phrases: ['changer taille de police petite', 'taille de police petite', 'police petite'], command: { type: 'fontSize', value: 2 } },
    { phrases: ['changer taille de police normale', 'taille de police normale', 'police normale', 'taille moyenne'], command: { type: 'fontSize', value: 3 } },
    { phrases: ['changer taille de police grande', 'taille de police grande', 'police grande'], command: { type: 'fontSize', value: 4 } },
    { phrases: ['changer taille de police très grande', 'taille de police très grande'], command: { type: 'fontSize', value: 5 } },
    { phrases: ['changer taille de police géante', 'taille de police géante', 'police géante'], command: { type: 'fontSize', value: 6 } },
    { phrases: ['aligner le texte à gauche', 'aligner le texte a gauche'], command: { type: 'justifyLeft' } },
    { phrases: ['aligner le texte au centre'], command: { type: 'justifyCenter' } },
    { phrases: ['aligner le texte à droite', 'aligner le texte a droite'], command: { type: 'justifyRight' } },
  ],
  pt: [
    { phrases: ['iniciar negrito', 'ativar negrito'], command: { type: 'bold', value: true } },
    { phrases: ['finalizar negrito', 'desativar negrito'], command: { type: 'bold', value: false } },
    { phrases: ['iniciar itálico', 'ativar itálico'], command: { type: 'italic', value: true } },
    { phrases: ['finalizar itálico', 'desativar itálico'], command: { type: 'italic', value: false } },
    { phrases: ['iniciar sublinhado', 'ativar sublinhado'], command: { type: 'underline', value: true } },
    { phrases: ['finalizar sublinhado', 'desativar sublinhado'], command: { type: 'underline', value: false } },
    { phrases: ['aumentar recuo', 'adicionar recuo'], command: { type: 'indent' } },
    { phrases: ['diminuir recuo', 'remover recuo'], command: { type: 'outdent' } },
    { phrases: ['inserir título 4', 'iniciar título 4'], command: { type: 'formatBlock', value: 'h4' } },
    { phrases: ['finalizar título 4', 'terminar título 4'], command: { type: 'formatBlock', value: 'p' } },
    { phrases: ['inserir título 3', 'iniciar título 3'], command: { type: 'formatBlock', value: 'h3' } },
    { phrases: ['finalizar título 3', 'terminar título 3'], command: { type: 'formatBlock', value: 'p' } },
    { phrases: ['inserir título 2', 'iniciar título 2'], command: { type: 'formatBlock', value: 'h2' } },
    { phrases: ['finalizar título 2', 'terminar título 2'], command: { type: 'formatBlock', value: 'p' } },
    { phrases: ['inserir título', 'iniciar título', 'inserir título 1', 'iniciar título 1'], command: { type: 'formatBlock', value: 'h1' } },
    { phrases: ['finalizar título', 'terminar título', 'finalizar título 1', 'terminar título 1'], command: { type: 'formatBlock', value: 'p' } },
    { phrases: ['mudar tamanho da fonte pequeno', 'tamanho da fonte pequeno', 'fonte pequena'], command: { type: 'fontSize', value: 2 } },
    { phrases: ['mudar tamanho da fonte normal', 'tamanho da fonte normal', 'fonte normal', 'tamanho médio'], command: { type: 'fontSize', value: 3 } },
    { phrases: ['mudar tamanho da fonte grande', 'tamanho da fonte grande', 'fonte grande'], command: { type: 'fontSize', value: 4 } },
    { phrases: ['mudar tamanho da fonte muito grande', 'tamanho da fonte muito grande'], command: { type: 'fontSize', value: 5 } },
    { phrases: ['mudar tamanho da fonte gigante', 'tamanho da fonte gigante', 'fonte gigante'], command: { type: 'fontSize', value: 6 } },
    { phrases: ['alinhar texto à esquerda', 'alinhar texto a esquerda'], command: { type: 'justifyLeft' } },
    { phrases: ['alinhar texto ao centro'], command: { type: 'justifyCenter' } },
    { phrases: ['alinhar texto à direita', 'alinhar texto a direita'], command: { type: 'justifyRight' } },
  ],
  it: [
    { phrases: ['attivare grassetto', 'iniziare grassetto'], command: { type: 'bold', value: true } },
    { phrases: ['disattivare grassetto', 'fine grassetto'], command: { type: 'bold', value: false } },
    { phrases: ['attivare corsivo', 'iniziare corsivo'], command: { type: 'italic', value: true } },
    { phrases: ['disattivare corsivo', 'fine corsivo'], command: { type: 'italic', value: false } },
    { phrases: ['attivare sottolineato', 'iniziare sottolineato'], command: { type: 'underline', value: true } },
    { phrases: ['disattivare sottolineato', 'fine sottolineato'], command: { type: 'underline', value: false } },
    { phrases: ['aumenta rientro', 'aggiungi rientro'], command: { type: 'indent' } },
    { phrases: ['diminuisci rientro', 'rimuovi rientro'], command: { type: 'outdent' } },
    { phrases: ['inserisci titolo 4', 'inizia titolo 4'], command: { type: 'formatBlock', value: 'h4' } },
    { phrases: ['fine titolo 4', 'termina titolo 4'], command: { type: 'formatBlock', value: 'p' } },
    { phrases: ['inserisci titolo 3', 'inizia titolo 3'], command: { type: 'formatBlock', value: 'h3' } },
    { phrases: ['fine titolo 3', 'termina titolo 3'], command: { type: 'formatBlock', value: 'p' } },
    { phrases: ['inserisci titolo 2', 'inizia titolo 2'], command: { type: 'formatBlock', value: 'h2' } },
    { phrases: ['fine titolo 2', 'termina titolo 2'], command: { type: 'formatBlock', value: 'p' } },
    { phrases: ['inserisci titolo', 'inizia titolo', 'inserisci titolo 1', 'inizia titolo 1'], command: { type: 'formatBlock', value: 'h1' } },
    { phrases: ['fine titolo', 'termina titolo', 'fine titolo 1', 'termina titolo 1'], command: { type: 'formatBlock', value: 'p' } },
    { phrases: ['cambia dimensione del carattere piccolo', 'dimensione del carattere piccolo', 'carattere piccolo'], command: { type: 'fontSize', value: 2 } },
    { phrases: ['cambia dimensione del carattere normale', 'dimensione del carattere normale', 'carattere medio'], command: { type: 'fontSize', value: 3 } },
    { phrases: ['cambia dimensione del carattere grande', 'dimensione del carattere grande', 'carattere grande'], command: { type: 'fontSize', value: 4 } },
    { phrases: ['cambia dimensione del carattere molto grande', 'dimensione del carattere molto grande'], command: { type: 'fontSize', value: 5 } },
    { phrases: ['cambia dimensione del carattere gigante', 'dimensione del carattere gigante', 'carattere gigante'], command: { type: 'fontSize', value: 6 } },
    { phrases: ['allinea il testo a sinistra'], command: { type: 'justifyLeft' } },
    { phrases: ['allinea il testo al centro'], command: { type: 'justifyCenter' } },
    { phrases: ['allinea il testo a destra'], command: { type: 'justifyRight' } },
  ],
  de: [
    { phrases: ['activate bold', 'fettschrift aktivieren'], command: { type: 'bold', value: true } },
    { phrases: ['deactivate bold', 'fettschrift deaktivieren'], command: { type: 'bold', value: false } },
    { phrases: ['activate italic', 'kursivschrift aktivieren'], command: { type: 'italic', value: true } },
    { phrases: ['deactivate italic', 'kursivschrift deaktivieren'], command: { type: 'italic', value: false } },
    { phrases: ['activate underline', 'unterstreichen aktivieren'], command: { type: 'underline', value: true } },
    { phrases: ['deactivate underline', 'unterstreichen deaktivieren'], command: { type: 'underline', value: false } },
    { phrases: ['einzug vergrößern', 'einzug hinzufügen'], command: { type: 'indent' } },
    { phrases: ['einzug verringern', 'einzug entfernen'], command: { type: 'outdent' } },
    { phrases: ['überschrift 4 einfügen'], command: { type: 'formatBlock', value: 'h4' } },
    { phrases: ['überschrift 4 beenden'], command: { type: 'formatBlock', value: 'p' } },
    { phrases: ['überschrift 3 einfügen'], command: { type: 'formatBlock', value: 'h3' } },
    { phrases: ['überschrift 3 beenden'], command: { type: 'formatBlock', value: 'p' } },
    { phrases: ['überschrift 2 einfügen'], command: { type: 'formatBlock', value: 'h2' } },
    { phrases: ['überschrift 2 beenden'], command: { type: 'formatBlock', value: 'p' } },
    { phrases: ['überschrift 1 einfügen', 'überschrift einfügen'], command: { type: 'formatBlock', value: 'h1' } },
    { phrases: ['überschrift 1 beenden', 'überschrift beenden'], command: { type: 'formatBlock', value: 'p' } },
    { phrases: ['schriftgröße klein', 'schriftgröße sehr klein'], command: { type: 'fontSize', value: 2 } },
    { phrases: ['schriftgröße normal', 'schriftgröße mittel'], command: { type: 'fontSize', value: 3 } },
    { phrases: ['schriftgröße groß'], command: { type: 'fontSize', value: 4 } },
    { phrases: ['schriftgröße sehr groß'], command: { type: 'fontSize', value: 5 } },
    { phrases: ['schriftgröße riesig'], command: { type: 'fontSize', value: 6 } },
    { phrases: ['linksbündig ausrichten', 'linksbündig'], command: { type: 'justifyLeft' } },
    { phrases: ['zentriert ausrichten', 'zentriert', 'text zentrieren'], command: { type: 'justifyCenter' } },
    { phrases: ['rechtsbündig ausrichten', 'rechtsbündig'], command: { type: 'justifyRight' } },
  ],
  ja: [
    { phrases: ['太字にする', '太字開始'], command: { type: 'bold', value: true } },
    { phrases: ['太字を解除する', '太字終了'], command: { type: 'bold', value: false } },
    { phrases: ['斜体にする', '斜体開始'], command: { type: 'italic', value: true } },
    { phrases: ['斜体を解除する', '斜体終了'], command: { type: 'italic', value: false } },
    { phrases: ['下線を引き', '下線開始'], command: { type: 'underline', value: true } },
    { phrases: ['下線を解除する', '下線終了'], command: { type: 'underline', value: false } },
    { phrases: ['インデントを増やす', 'インデント追加'], command: { type: 'indent' } },
    { phrases: ['インデントを減らす', 'インデント解除'], command: { type: 'outdent' } },
    { phrases: ['見出し4を入力する', '見出し4開始'], command: { type: 'formatBlock', value: 'h4' } },
    { phrases: ['見出し4を終了する'], command: { type: 'formatBlock', value: 'p' } },
    { phrases: ['見出し3を入力する', '見出し3開始'], command: { type: 'formatBlock', value: 'h3' } },
    { phrases: ['見出し3を終了する'], command: { type: 'formatBlock', value: 'p' } },
    { phrases: ['見出し2を入力する', '見出し2開始'], command: { type: 'formatBlock', value: 'h2' } },
    { phrases: ['見出し2を終了する'], command: { type: 'formatBlock', value: 'p' } },
    { phrases: ['見出し1を入力する', '見出しを入力する', '見出し開始'], command: { type: 'formatBlock', value: 'h1' } },
    { phrases: ['見出し1を終了する', '見出しを終了する', '見出し終了'], command: { type: 'formatBlock', value: 'p' } },
    { phrases: ['文字サイズを小さくする', '小さい文字サイズ'], command: { type: 'fontSize', value: 2 } },
    { phrases: ['文字サイズを普通にする', '普通の文字サイズ'], command: { type: 'fontSize', value: 3 } },
    { phrases: ['文字サイズを大きくする', '大きい文字サイズ'], command: { type: 'fontSize', value: 4 } },
    { phrases: ['文字サイズを非常に大きくする'], command: { type: 'fontSize', value: 5 } },
    { phrases: ['文字サイズを最大にする', '巨大な文字サイズ'], command: { type: 'fontSize', value: 6 } },
    { phrases: ['左に寄せる', '左揃え'], command: { type: 'justifyLeft' } },
    { phrases: ['中央に寄せる', '中央揃え', 'センタリング'], command: { type: 'justifyCenter' } },
    { phrases: ['右に寄せる', '右揃え'], command: { type: 'justifyRight' } },
  ]
};

export interface HelpCommandItem {
  phrase: string;
  result: string;
  isFormat?: boolean;
}

export interface HelpCategory {
  id: string;
  name: Record<string, string>;
  items: HelpCommandItem[];
}

// Categorización y ordenación inteligente de los comandos
export function getVoiceCommandsByCategory(lang: string): HelpCategory[] {
  // Normalizar código de idioma de 2 caracteres
  const langCode = lang.split('-')[0].toLowerCase();

  // Textos traducidos de las categorías para renderizado directo
  const CATEGORY_NAMES: Record<string, Record<string, string>> = {
    basic: {
      es: 'Más Usados / Básicos',
      en: 'Most Used / Basics',
      fr: 'Les Plus Utilisés / Basiques',
      pt: 'Mais Usados / Básicos',
      it: 'Più Usati / Base',
      de: 'Am häufigsten verwendet / Grundlagen',
      ja: 'よく使うコマンド / 基本'
    },
    punctuation: {
      es: 'Preguntas y Exclamaciones',
      en: 'Questions and Exclamations',
      fr: 'Questions et Exclamations',
      pt: 'Perguntas e Exclamações',
      it: 'Domande ed Esclamazioni',
      de: 'Fragen und Ausrufe',
      ja: '疑問符・感嘆符'
    },
    symbols: {
      es: 'Símbolos y Estructura',
      en: 'Symbols and Formatting',
      fr: 'Symboles et Formatage',
      pt: 'Símbolos e Formatação',
      it: 'Simboli e Formattazione',
      de: 'Symbole und Formatierung',
      ja: '記号・フォーマット'
    },
    math: {
      es: 'Operadores Matemáticos',
      en: 'Mathematical Operators',
      fr: 'Opérateurs Mathématiques',
      pt: 'Operadores Matemáticos',
      it: 'Operatori Matematici',
      de: 'Mathematische Operatoren',
      ja: '数学記号'
    },
    editing: {
      es: 'Edición y Formato de Texto',
      en: 'Text Formatting & Editing',
      fr: 'Formatage et Édition de Texte',
      pt: 'Formatação e Edição de Texto',
      it: 'Modifica e Formattazione del Testo',
      de: 'Textformatierung & Bearbeitung',
      ja: 'テキスト編集・フォーマット'
    },
    web: {
      es: 'Web y Dominios',
      en: 'Web & Domains',
      fr: 'Web et Domaines',
      pt: 'Web e Domínios',
      it: 'Web e Domini',
      de: 'Web & Domains',
      ja: 'ウェブ・ドメイン'
    }
  };

  const getCatName = (catId: string) => CATEGORY_NAMES[catId]?.[langCode] || CATEGORY_NAMES[catId]?.['en'] || catId;

  const punctuationMap = RAW_PUNCTUATION[langCode] || RAW_PUNCTUATION['en'];
  const formatsList = RAW_FORMATS[langCode] || RAW_FORMATS['en'];

  // Agrupamiento inicial de puntuaciones
  const basicItems: HelpCommandItem[] = [];
  const questionItems: HelpCommandItem[] = [];
  const symbolItems: HelpCommandItem[] = [];
  const mathItems: HelpCommandItem[] = [];
  const webItems: HelpCommandItem[] = [];

  for (const [phrase, result] of Object.entries(punctuationMap)) {
    const item = { phrase, result: result.replace('\n\n', '\\n\\n').replace('\n', '\\n') };

    // Clasificar inteligentemente
    if (result.includes('\n') || ['punto', 'coma', 'punto y seguido', 'punto seguido', 'punto final', 'period', 'full stop', 'dot', 'comma'].includes(phrase)) {
      basicItems.push(item);
    } else if (['?', '!', '¿', '¡'].includes(result.trim()) || phrase.includes('interrogación') || phrase.includes('exclamación') || phrase.includes('pregunta') || phrase.includes('admiración') || phrase.includes('question') || phrase.includes('exclamation')) {
      questionItems.push(item);
    } else if (['+', '-', '='].includes(result.trim()) || phrase.includes('más') || phrase.includes('menos') || phrase.includes('igual') || phrase.includes('plus') || phrase.includes('minus') || phrase.includes('equal') || phrase.includes('suma') || phrase.includes('resta')) {
      mathItems.push(item);
    } else if (result.startsWith('.')) {
      webItems.push(item);
    } else {
      symbolItems.push(item);
    }
  }

  // Agrupamiento de formatos
  const editingItems: HelpCommandItem[] = [];
  for (const fmt of formatsList) {
    for (const phrase of fmt.phrases) {
      let desc = '';
      if (langCode === 'es') {
        desc = fmt.command.type === 'bold' ? (fmt.command.value ? 'Negrita (Activar)' : 'Negrita (Desactivar)')
          : fmt.command.type === 'italic' ? (fmt.command.value ? 'Cursiva (Activar)' : 'Cursiva (Desactivar)')
            : fmt.command.type === 'underline' ? (fmt.command.value ? 'Subrayado (Activar)' : 'Subrayado (Desactivar)')
              : fmt.command.type === 'indent' ? 'Aumentar sangría'
                : fmt.command.type === 'outdent' ? 'Disminuir sangría'
                  : fmt.command.type === 'formatBlock' ? (fmt.command.value === 'p' ? 'Establecer párrafo normal' : `Establecer título ${fmt.command.value.replace('h', '')}`)
                    : fmt.command.type === 'fontSize' ? `Tamaño de fuente nivel ${fmt.command.value}`
                      : fmt.command.type === 'justifyLeft' ? 'Alinear a la izquierda'
                        : fmt.command.type === 'justifyCenter' ? 'Centrar texto'
                          : 'Alinear a la derecha';
      } else {
        desc = fmt.command.type === 'bold' ? (fmt.command.value ? 'Bold (On)' : 'Bold (Off)')
          : fmt.command.type === 'italic' ? (fmt.command.value ? 'Italic (On)' : 'Italic (Off)')
            : fmt.command.type === 'underline' ? (fmt.command.value ? 'Underline (On)' : 'Underline (Off)')
              : fmt.command.type === 'indent' ? 'Increase indent'
                : fmt.command.type === 'outdent' ? 'Decrease indent'
                  : fmt.command.type === 'formatBlock' ? (fmt.command.value === 'p' ? 'Set normal paragraph' : `Set Heading ${fmt.command.value.replace('h', '')}`)
                    : fmt.command.type === 'fontSize' ? `Font size level ${fmt.command.value}`
                      : fmt.command.type === 'justifyLeft' ? 'Align left'
                        : fmt.command.type === 'justifyCenter' ? 'Center text'
                          : 'Align right';
      }
      editingItems.push({ phrase, result: desc, isFormat: true });
    }
  }

  // Retornar las categorías ordenadas
  return [
    { id: 'basic', name: { [langCode]: getCatName('basic') }, items: basicItems },
    { id: 'punctuation', name: { [langCode]: getCatName('punctuation') }, items: questionItems },
    { id: 'editing', name: { [langCode]: getCatName('editing') }, items: editingItems },
    { id: 'symbols', name: { [langCode]: getCatName('symbols') }, items: symbolItems },
    { id: 'math', name: { [langCode]: getCatName('math') }, items: mathItems },
    { id: 'web', name: { [langCode]: getCatName('web') }, items: webItems }
  ];
}
