import React from "react";
import { render, screen, fireEvent, waitFor } from "@testing-library/react";
import { ThemeProvider } from "styled-components";
import { Breadcrumb, useBreadcrumbNavigation, useBreadcrumbCollapse } from "./index";
import {
  SmallBreadcrumb,
  MediumBreadcrumb,
  LargeBreadcrumbComponent,
  PrimaryBreadcrumb,
  SecondaryBreadcrumb,
  ArrowBreadcrumb,
  ChevronBreadcrumb,
  SlashBreadcrumb,
  DotBreadcrumb,
  ResponsiveBreadcrumbComponent,
  CollapsibleBreadcrumb,
  AutoGeneratedBreadcrumb,
  NavigationBreadcrumbComponent,
  SimpleBreadcrumbComponent,
  CompactBreadcrumbComponent,
  CardBreadcrumbComponent,
  MobileBreadcrumbComponent,
  MinimalBreadcrumbComponent,
  HighContrastBreadcrumbComponent,
  LargeTextBreadcrumbComponent,
  ReducedMotionBreadcrumb,
  MultiLevelBreadcrumb,
  InteractiveBreadcrumb,
  LoadingBreadcrumb,
} from "./index";
import { BreadcrumbItem, BREADCRUMB_DEFAULTS } from "./Breadcrumb.types";

// =============================================================================
// MOCKS
// =============================================================================

jest.mock("../../../../hooks/useThemeColors", () => {
  const mockThemeColors = {
    primary: {
      50: "#e3f2fd",
      100: "#bbdefb",
      200: "#90caf9",
      500: "#1976d2",
      600: "#1565c0",
      700: "#0d47a1",
    },
    secondary: {
      50: "#fce4ec",
      100: "#f8bbd9",
      200: "#f48fb1",
      500: "#dc004e",
      600: "#c51162",
      700: "#880e4f",
    },
    success: {
      50: "#e8f5e8",
      100: "#c8e6c9",
      200: "#81c784",
      500: "#2e7d32",
      600: "#1b5e20",
      700: "#1b5e20",
    },
    warning: {
      50: "#fff3e0",
      100: "#ffe0b2",
      200: "#ffb74d",
      500: "#ed6c02",
      600: "#e65100",
      700: "#bf360c",
    },
    error: {
      50: "#ffebee",
      100: "#ffcdd2",
      200: "#ef5350",
      500: "#d32f2f",
      600: "#c62828",
      700: "#b71c1c",
    },
    info: {
      50: "#e1f5fe",
      100: "#b3e5fc",
      200: "#4fc3f7",
      500: "#0288d1",
      600: "#0277bd",
      700: "#01579b",
    },
    neutral: {
      50: "#fafafa",
      100: "#f5f5f5",
      200: "#eeeeee",
      300: "#e0e0e0",
      400: "#bdbdbd",
      500: "#9e9e9e",
      600: "#757575",
    },
    background: {
      primary: "#ffffff",
      secondary: "#f5f5f5",
      tertiary: "#e0e0e0",
    },
    text: {
      primary: "#212121",
      secondary: "#757575",
      disabled: "#bdbdbd",
    },
    border: {
      normal: "#e0e0e0",
      light: "#f0f0f0",
      dark: "#bdbdbd",
    },
    gradients: {
      primary: "linear-gradient(135deg, #1976d2 0%, #1565c0 100%)",
      secondary: "linear-gradient(135deg, #dc004e 0%, #c51162 100%)",
    },
    overlay: "rgba(0,0,0,0.45)",
    shadow: {
      sm: "0 1px 2px rgba(0,0,0,0.12)",
      md: "0 2px 4px rgba(0,0,0,0.12)",
      lg: "0 4px 8px rgba(0,0,0,0.12)",
    },
  };

  return {
    __esModule: true,
    useThemeColors: () => mockThemeColors,
  };
});

// Theme for testing
const testTheme = {
  colors: {
    primary: { 500: "#1976d2" },
    background: { primary: "#ffffff", secondary: "#f5f5f5" },
    text: { primary: "#212121", secondary: "#757575" },
    border: { normal: "#e0e0e0", light: "#f0f0f0" },
  },
};

// =============================================================================
// TEST UTILITIES
// =============================================================================

const renderBreadcrumb = (ui: React.ReactElement) => {
  return render(
    <ThemeProvider theme={testTheme as any}>
      {ui}
    </ThemeProvider>
  );
};

// Sample breadcrumb items
const sampleItems: BreadcrumbItem[] = [
  {
    key: "home",
    title: "Home",
    href: "/",
  },
  {
    key: "products",
    title: "Products",
    href: "/products",
  },
  {
    key: "category",
    title: "Electronics",
    href: "/products/electronics",
  },
  {
    key: "current",
    title: "Smartphones",
  },
];

const sampleItemsWithIcons: BreadcrumbItem[] = [
  {
    key: "home",
    title: "Home",
    href: "/",
    icon: <span data-testid="home-icon">🏠</span>,
  },
  {
    key: "products",
    title: "Products",
    href: "/products",
    icon: <span data-testid="products-icon">📦</span>,
  },
  {
    key: "current",
    title: "Current Page",
  },
];

// =============================================================================
// BASIC TESTS
// =============================================================================

describe("Breadcrumb", () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  // ---------------------------------------------------------------------------
  // RENDERING TESTS
  // ---------------------------------------------------------------------------

  it("renders correctly", () => {
    renderBreadcrumb(<Breadcrumb items={sampleItems} />);
    const nav = screen.getByRole("navigation");
    expect(nav).toBeInTheDocument();
    expect(nav).toHaveAttribute("aria-label", "Breadcrumb navigation");
  });

  it("renders with custom className", () => {
    renderBreadcrumb(<Breadcrumb items={sampleItems} className="custom-class" />);
    const nav = screen.getByRole("navigation");
    expect(nav).toHaveClass("breadcrumb", "custom-class");
  });

  it("renders with custom style", () => {
    const customStyle = { backgroundColor: "red" };
    renderBreadcrumb(<Breadcrumb items={sampleItems} style={customStyle} />);
    const nav = screen.getByRole("navigation");
    expect(nav).toHaveStyle("background-color: red");
  });

  it("renders breadcrumb items", () => {
    renderBreadcrumb(<Breadcrumb items={sampleItems} />);
    
    expect(screen.getByText("Home")).toBeInTheDocument();
    expect(screen.getByText("Products")).toBeInTheDocument();
    expect(screen.getByText("Electronics")).toBeInTheDocument();
    expect(screen.getByText("Smartphones")).toBeInTheDocument();
  });

  it("renders items with routes prop", () => {
    renderBreadcrumb(<Breadcrumb routes={sampleItems} />);
    
    expect(screen.getByText("Home")).toBeInTheDocument();
    expect(screen.getByText("Products")).toBeInTheDocument();
  });

  it("renders with icons", () => {
    renderBreadcrumb(<Breadcrumb items={sampleItemsWithIcons} />);
    
    expect(screen.getByTestId("home-icon")).toBeInTheDocument();
    expect(screen.getByTestId("products-icon")).toBeInTheDocument();
  });

  it("renders children", () => {
    renderBreadcrumb(
      <Breadcrumb items={sampleItems}>
        <span>Custom content</span>
      </Breadcrumb>
    );
    expect(screen.getByText("Custom content")).toBeInTheDocument();
  });

  // ---------------------------------------------------------------------------
  // SIZE TESTS
  // ---------------------------------------------------------------------------

  it("applies size prop correctly", () => {
    const sizes = ["xs", "sm", "md", "lg", "xl", "xxl"] as const;
    
    sizes.forEach((size) => {
      const { unmount } = renderBreadcrumb(<Breadcrumb items={sampleItems} size={size} />);
      const nav = screen.getByRole("navigation");
      expect(nav).toHaveAttribute("data-size", size);
      unmount();
    });
  });

  // ---------------------------------------------------------------------------
  // VARIANT TESTS
  // ---------------------------------------------------------------------------

  it("applies variant prop correctly", () => {
    const variants = ["primary", "secondary", "success", "warning", "error", "info", "ghost"] as const;
    
    variants.forEach((variant) => {
      const { unmount } = renderBreadcrumb(<Breadcrumb items={sampleItems} variant={variant} />);
      const nav = screen.getByRole("navigation");
      expect(nav).toHaveAttribute("data-variant", variant);
      unmount();
    });
  });

  // ---------------------------------------------------------------------------
  // SEPARATOR TESTS
  // ---------------------------------------------------------------------------

  it("renders with default separator", () => {
    renderBreadcrumb(<Breadcrumb items={sampleItems} />);
    // Separators are rendered between items (3 items = 2 separators)
    const separators = document.querySelectorAll(".breadcrumb-separator");
    expect(separators).toHaveLength(3); // 4 items - 1 = 3 separators
  });

  it("renders with arrow separator", () => {
    renderBreadcrumb(<Breadcrumb items={sampleItems} separator="arrow" />);
    const separator = document.querySelector(".breadcrumb-separator");
    expect(separator).toBeInTheDocument();
  });

  it("renders with chevron separator", () => {
    renderBreadcrumb(<Breadcrumb items={sampleItems} separator="chevron" />);
    const separator = document.querySelector(".breadcrumb-separator");
    expect(separator).toBeInTheDocument();
  });

  it("renders with custom separator", () => {
    const customSeparator = <span data-testid="custom-sep">→</span>;
    renderBreadcrumb(<Breadcrumb items={sampleItems} separator={customSeparator} />);
    expect(screen.getAllByTestId("custom-sep")).toHaveLength(3);
  });

  // ---------------------------------------------------------------------------
  // CLICK BEHAVIOR TESTS
  // ---------------------------------------------------------------------------

  it("handles item clicks", () => {
    const handleClick = jest.fn();
    renderBreadcrumb(<Breadcrumb items={sampleItems} onClick={handleClick} />);
    
    const homeLink = screen.getByText("Home").closest("a");
    if (homeLink) {
      fireEvent.click(homeLink);
      expect(handleClick).toHaveBeenCalledTimes(1);
    }
  });

  it("handles onItemClick", () => {
    const handleItemClick = jest.fn();
    renderBreadcrumb(<Breadcrumb items={sampleItems} onItemClick={handleItemClick} />);
    
    const homeLink = screen.getByText("Home").closest("a");
    if (homeLink) {
      fireEvent.click(homeLink);
      expect(handleItemClick).toHaveBeenCalledTimes(1);
    }
  });

  it("handles disabled items", () => {
    const disabledItems = [
      ...sampleItems.slice(0, 2),
      { ...sampleItems[2], disabled: true },
      sampleItems[3],
    ];
    
    const handleClick = jest.fn();
    renderBreadcrumb(<Breadcrumb items={disabledItems} onClick={handleClick} />);
    
    const disabledItem = screen.getByText("Electronics");
    fireEvent.click(disabledItem);
    
    // Click should not be handled for disabled items
    expect(handleClick).not.toHaveBeenCalled();
  });

  it("handles custom onClick for items", () => {
    const customClick = jest.fn();
    const itemsWithClick = [
      { ...sampleItems[0], onClick: customClick },
      ...sampleItems.slice(1),
    ];
    
    renderBreadcrumb(<Breadcrumb items={itemsWithClick} />);
    
    const homeItem = screen.getByText("Home");
    fireEvent.click(homeItem);
    
    expect(customClick).toHaveBeenCalledTimes(1);
  });

  // ---------------------------------------------------------------------------
  // KEYBOARD BEHAVIOR TESTS
  // ---------------------------------------------------------------------------

  it("handles keyboard navigation", () => {
    const handleClick = jest.fn();
    renderBreadcrumb(<Breadcrumb items={sampleItems} onClick={handleClick} />);
    
    const homeItem = screen.getByText("Home").closest("[role='button']");
    if (homeItem) {
      fireEvent.keyDown(homeItem, { key: "Enter" });
      expect(handleClick).toHaveBeenCalledTimes(1);
    }
  });

  it("handles space key", () => {
    const handleClick = jest.fn();
    renderBreadcrumb(<Breadcrumb items={sampleItems} onClick={handleClick} />);
    
    const homeItem = screen.getByText("Home").closest("[role='button']");
    if (homeItem) {
      fireEvent.keyDown(homeItem, { key: " " });
      expect(handleClick).toHaveBeenCalledTimes(1);
    }
  });

  // ---------------------------------------------------------------------------
  // COLLAPSE TESTS
  // ---------------------------------------------------------------------------

  it("collapses items when maxItems is set", () => {
    renderBreadcrumb(<Breadcrumb items={sampleItems} maxItems={3} />);
    
    // Should show collapsed indicator
    const expandButton = screen.getByText("...");
    expect(expandButton).toBeInTheDocument();
  });

  it("expands collapsed items on click", () => {
    renderBreadcrumb(<Breadcrumb items={sampleItems} maxItems={2} />);
    
    const expandButton = screen.getByText("...");
    fireEvent.click(expandButton);
    
    // Should show dropdown or expanded items
    // This depends on implementation details
  });

  it("handles expandText prop", () => {
    renderBreadcrumb(
      <Breadcrumb 
        items={sampleItems} 
        maxItems={2} 
        expandText="Show more" 
      />
    );
    
    expect(screen.getByText("Show more")).toBeInTheDocument();
  });

  // ---------------------------------------------------------------------------
  // RESPONSIVE TESTS
  // ---------------------------------------------------------------------------

  it("applies responsive prop", () => {
    renderBreadcrumb(<Breadcrumb items={sampleItems} responsive={true} />);
    
    const nav = screen.getByRole("navigation");
    expect(nav).toHaveAttribute("data-responsive", "true");
  });

  // ---------------------------------------------------------------------------
  // AUTO GENERATION TESTS
  // ---------------------------------------------------------------------------

  it("auto-generates breadcrumbs when enabled", () => {
    // Mock window.location
    Object.defineProperty(window, "location", {
      value: { pathname: "/products/electronics/smartphones" },
      writable: true,
    });

    renderBreadcrumb(<Breadcrumb autoGenerate={true} />);
    
    expect(screen.getByText("Home")).toBeInTheDocument();
    expect(screen.getByText("Products")).toBeInTheDocument();
    expect(screen.getByText("Electronics")).toBeInTheDocument();
    expect(screen.getByText("Smartphones")).toBeInTheDocument();
  });

  it("uses custom home settings for auto-generation", () => {
    Object.defineProperty(window, "location", {
      value: { pathname: "/products" },
      writable: true,
    });

    renderBreadcrumb(
      <Breadcrumb 
        autoGenerate={true} 
        homeName="Dashboard" 
        homeUrl="/dashboard" 
      />
    );
    
    expect(screen.getByText("Dashboard")).toBeInTheDocument();
  });

  // ---------------------------------------------------------------------------
  // CUSTOM RENDERING TESTS
  // ---------------------------------------------------------------------------

  it("uses custom itemRender", () => {
    const customRender = (item: any) => (
      <span data-testid={`custom-${item.key}`}>
        Custom: {item.title}
      </span>
    );

    renderBreadcrumb(
      <Breadcrumb items={sampleItems} itemRender={customRender} />
    );
    
    expect(screen.getByTestId("custom-home")).toBeInTheDocument();
    expect(screen.getByText("Custom: Home")).toBeInTheDocument();
  });

  // ---------------------------------------------------------------------------
  // ACCESSIBILITY TESTS
  // ---------------------------------------------------------------------------

  it("has proper ARIA attributes", () => {
    renderBreadcrumb(<Breadcrumb items={sampleItems} />);
    
    const nav = screen.getByRole("navigation");
    expect(nav).toHaveAttribute("aria-label", "Breadcrumb navigation");
    expect(nav).toHaveAttribute("role", "navigation");
  });

  it("applies accessibility props", () => {
    renderBreadcrumb(
      <Breadcrumb 
        items={sampleItems}
        accessibility={{
          highContrast: true,
          largeText: true,
          reducedMotion: true,
        }}
      />
    );
    
    const nav = screen.getByRole("navigation");
    expect(nav).toBeInTheDocument();
  });

  // ---------------------------------------------------------------------------
  // REF TESTS
  // ---------------------------------------------------------------------------

  it("exposes ref methods", () => {
    const ref = React.createRef<any>();
    renderBreadcrumb(<Breadcrumb items={sampleItems} ref={ref} />);
    
    expect(ref.current).toHaveProperty("navigate");
    expect(ref.current).toHaveProperty("goHome");
    expect(ref.current).toHaveProperty("goBack");
    expect(ref.current).toHaveProperty("element");
    
    expect(typeof ref.current.navigate).toBe("function");
    expect(typeof ref.current.goHome).toBe("function");
    expect(typeof ref.current.goBack).toBe("function");
  });

  it("navigate method works via ref", () => {
    const ref = React.createRef<any>();
    const handleClick = jest.fn();
    renderBreadcrumb(<Breadcrumb items={sampleItems} onClick={handleClick} ref={ref} />);
    
    ref.current.navigate(sampleItems[0]);
    
    expect(handleClick).toHaveBeenCalledWith(sampleItems[0], expect.any(Object));
  });
});

// =============================================================================
// PREDEFINED COMPONENT TESTS
// =============================================================================

describe("Breadcrumb Predefined Components", () => {
  // ---------------------------------------------------------------------------
  // SIZE VARIANTS
  // ---------------------------------------------------------------------------

  it("renders SmallBreadcrumb correctly", () => {
    renderBreadcrumb(<SmallBreadcrumb items={sampleItems} />);
    const nav = screen.getByRole("navigation");
    expect(nav).toHaveAttribute("data-size", "sm");
  });

  it("renders MediumBreadcrumb correctly", () => {
    renderBreadcrumb(<MediumBreadcrumb items={sampleItems} />);
    const nav = screen.getByRole("navigation");
    expect(nav).toHaveAttribute("data-size", "md");
  });

  it("renders LargeBreadcrumb correctly", () => {
    renderBreadcrumb(<LargeBreadcrumbComponent items={sampleItems} />);
    const nav = screen.getByRole("navigation");
    expect(nav).toHaveAttribute("data-size", "lg");
  });

  // ---------------------------------------------------------------------------
  // VARIANT STYLES
  // ---------------------------------------------------------------------------

  it("renders PrimaryBreadcrumb correctly", () => {
    renderBreadcrumb(<PrimaryBreadcrumb items={sampleItems} />);
    const nav = screen.getByRole("navigation");
    expect(nav).toHaveAttribute("data-variant", "primary");
  });

  it("renders SecondaryBreadcrumb correctly", () => {
    renderBreadcrumb(<SecondaryBreadcrumb items={sampleItems} />);
    const nav = screen.getByRole("navigation");
    expect(nav).toHaveAttribute("data-variant", "secondary");
  });

  // ---------------------------------------------------------------------------
  // SEPARATOR VARIANTS
  // ---------------------------------------------------------------------------

  it("renders ArrowBreadcrumb correctly", () => {
    renderBreadcrumb(<ArrowBreadcrumb items={sampleItems} />);
    const nav = screen.getByRole("navigation");
    expect(nav).toHaveAttribute("data-separator", "arrow");
  });

  it("renders ChevronBreadcrumb correctly", () => {
    renderBreadcrumb(<ChevronBreadcrumb items={sampleItems} />);
    const nav = screen.getByRole("navigation");
    expect(nav).toHaveAttribute("data-separator", "chevron");
  });

  it("renders SlashBreadcrumb correctly", () => {
    renderBreadcrumb(<SlashBreadcrumb items={sampleItems} />);
    const nav = screen.getByRole("navigation");
    expect(nav).toHaveAttribute("data-separator", "slash");
  });

  it("renders DotBreadcrumb correctly", () => {
    renderBreadcrumb(<DotBreadcrumb items={sampleItems} />);
    const nav = screen.getByRole("navigation");
    expect(nav).toHaveAttribute("data-separator", "dot");
  });

  // ---------------------------------------------------------------------------
  // BEHAVIOR VARIANTS
  // ---------------------------------------------------------------------------

  it("renders ResponsiveBreadcrumb correctly", () => {
    renderBreadcrumb(<ResponsiveBreadcrumbComponent items={sampleItems} />);
    const nav = screen.getByRole("navigation");
    expect(nav).toHaveAttribute("data-responsive", "true");
  });

  it("renders CollapsibleBreadcrumb correctly", () => {
    renderBreadcrumb(<CollapsibleBreadcrumb items={sampleItems} />);
    const nav = screen.getByRole("navigation");
    expect(nav).toHaveAttribute("data-max-items", "4");
    expect(nav).toHaveAttribute("data-responsive", "true");
  });

  it("renders AutoGeneratedBreadcrumb correctly", () => {
    Object.defineProperty(window, "location", {
      value: { pathname: "/test" },
      writable: true,
    });

    renderBreadcrumb(<AutoGeneratedBreadcrumb />);
    expect(screen.getByText("Home")).toBeInTheDocument();
    expect(screen.getByText("Test")).toBeInTheDocument();
  });

  // ---------------------------------------------------------------------------
  // USE CASE VARIANTS
  // ---------------------------------------------------------------------------

  it("renders NavigationBreadcrumb correctly", () => {
    Object.defineProperty(window, "location", {
      value: { pathname: "/products" },
      writable: true,
    });

    renderBreadcrumb(<NavigationBreadcrumbComponent />);
    expect(screen.getByText("Home")).toBeInTheDocument();
    expect(screen.getByText("Products")).toBeInTheDocument();
  });

  it("renders SimpleBreadcrumb correctly", () => {
    renderBreadcrumb(<SimpleBreadcrumbComponent items={sampleItems} />);
    const nav = screen.getByRole("navigation");
    expect(nav).toHaveAttribute("data-variant", "secondary");
    expect(nav).toHaveAttribute("data-separator", "slash");
    expect(nav).toHaveAttribute("data-size", "md");
  });

  it("renders CompactBreadcrumb correctly", () => {
    renderBreadcrumb(<CompactBreadcrumbComponent items={sampleItems} />);
    const nav = screen.getByRole("navigation");
    expect(nav).toHaveAttribute("data-size", "sm");
    expect(nav).toHaveAttribute("data-separator", "dot");
    expect(nav).toHaveAttribute("data-max-items", "3");
  });

  it("renders CardBreadcrumb correctly", () => {
    renderBreadcrumb(<CardBreadcrumbComponent items={sampleItems} />);
    const nav = screen.getByRole("navigation");
    expect(nav).toHaveAttribute("data-variant", "primary");
    expect(nav).toHaveAttribute("data-separator", "chevron");
    expect(nav).toHaveAttribute("data-responsive", "true");
  });

  it("renders MobileBreadcrumb correctly", () => {
    renderBreadcrumb(<MobileBreadcrumbComponent items={sampleItems} />);
    const nav = screen.getByRole("navigation");
    expect(nav).toHaveAttribute("data-size", "sm");
    expect(nav).toHaveAttribute("data-responsive", "true");
    expect(nav).toHaveAttribute("data-max-items", "2");
  });

  it("renders MinimalBreadcrumb correctly", () => {
    renderBreadcrumb(<MinimalBreadcrumbComponent items={sampleItems} />);
    const nav = screen.getByRole("navigation");
    expect(nav).toHaveAttribute("data-variant", "ghost");
    expect(nav).toHaveAttribute("data-separator", "slash");
    expect(nav).toHaveAttribute("data-size", "sm");
  });

  // ---------------------------------------------------------------------------
  // ACCESSIBILITY VARIANTS
  // ---------------------------------------------------------------------------

  it("renders HighContrastBreadcrumb correctly", () => {
    renderBreadcrumb(<HighContrastBreadcrumbComponent items={sampleItems} />);
    const nav = screen.getByRole("navigation");
    expect(nav).toHaveAttribute("data-variant", "primary");
    expect(nav).toHaveAttribute("data-size", "lg");
  });

  it("renders LargeTextBreadcrumb correctly", () => {
    renderBreadcrumb(<LargeTextBreadcrumbComponent items={sampleItems} />);
    const nav = screen.getByRole("navigation");
    expect(nav).toHaveAttribute("data-size", "xl");
  });

  it("renders ReducedMotionBreadcrumb correctly", () => {
    renderBreadcrumb(<ReducedMotionBreadcrumb items={sampleItems} />);
    const nav = screen.getByRole("navigation");
    expect(nav).toBeInTheDocument();
  });

  // ---------------------------------------------------------------------------
  // ADVANCED VARIANTS
  // ---------------------------------------------------------------------------

  it("renders MultiLevelBreadcrumb correctly", () => {
    Object.defineProperty(window, "location", {
      value: { pathname: "/products/electronics/smartphones" },
      writable: true,
    });

    renderBreadcrumb(<MultiLevelBreadcrumb />);
    expect(screen.getByText("Home")).toBeInTheDocument();
    expect(screen.getByText("Products")).toBeInTheDocument();
    expect(screen.getByText("Electronics")).toBeInTheDocument();
    expect(screen.getByText("Smartphones")).toBeInTheDocument();
  });

  it("renders InteractiveBreadcrumb correctly", () => {
    const handleNavigate = jest.fn();
    renderBreadcrumb(
      <InteractiveBreadcrumb 
        items={sampleItems} 
        onNavigate={handleNavigate} 
      />
    );
    
    const homeLink = screen.getByText("Home").closest("a");
    if (homeLink) {
      fireEvent.click(homeLink);
      expect(handleNavigate).toHaveBeenCalledTimes(1);
    }
  });

  it("renders LoadingBreadcrumb correctly", () => {
    renderBreadcrumb(<LoadingBreadcrumb />);
    // Loading state should render skeleton
    expect(document.querySelector(".breadcrumb-skeleton-item")).toBeInTheDocument();
  });
});

// =============================================================================
// HOOK TESTS
// =============================================================================

describe("useBreadcrumbNavigation", () => {
  it("returns navigation utilities", () => {
    let hookResult: any;
    
    function TestComponent() {
      hookResult = useBreadcrumbNavigation(sampleItems);
      return <div>Test</div>;
    }
    
    renderBreadcrumb(<TestComponent />);
    
    expect(hookResult.items).toEqual(sampleItems);
    expect(hookResult.currentPath).toBe("");
    expect(typeof hookResult.navigate).toBe("function");
    expect(typeof hookResult.goHome).toBe("function");
    expect(typeof hookResult.goBack).toBe("function");
  });

  it("handles navigation", () => {
    let hookResult: any;
    const onNavigate = jest.fn();
    
    function TestComponent() {
      hookResult = useBreadcrumbNavigation(sampleItems, onNavigate);
      return <div>Test</div>;
    }
    
    renderBreadcrumb(<TestComponent />);
    
    hookResult.navigate(sampleItems[0]);
    expect(onNavigate).toHaveBeenCalledWith(sampleItems[0]);
  });

  it("handles goHome", () => {
    let hookResult: any;
    const onNavigate = jest.fn();
    
    function TestComponent() {
      hookResult = useBreadcrumbNavigation(sampleItems, onNavigate);
      return <div>Test</div>;
    }
    
    renderBreadcrumb(<TestComponent />);
    
    hookResult.goHome();
    expect(onNavigate).toHaveBeenCalledWith(sampleItems[0]); // First item should be home
  });

  it("handles goBack", () => {
    let hookResult: any;
    const onNavigate = jest.fn();
    
    function TestComponent() {
      hookResult = useBreadcrumbNavigation(sampleItems, onNavigate);
      return <div>Test</div>;
    }
    
    renderBreadcrumb(<TestComponent />);
    
    hookResult.goBack();
    expect(onNavigate).toHaveBeenCalledWith(sampleItems[2]); // Second to last item
  });
});

describe("useBreadcrumbCollapse", () => {
  it("returns collapse utilities", () => {
    let hookResult: any;
    
    function TestComponent() {
      hookResult = useBreadcrumbCollapse(sampleItems, 3);
      return <div>Test</div>;
    }
    
    renderBreadcrumb(<TestComponent />);
    
    expect(Array.isArray(hookResult.visibleItems)).toBe(true);
    expect(Array.isArray(hookResult.collapsedItems)).toBe(true);
    expect(typeof hookResult.isCollapsed).toBe("boolean");
    expect(typeof hookResult.expand).toBe("function");
    expect(typeof hookResult.collapse).toBe("function");
  });

  it("collapses when needed", () => {
    let hookResult: any;
    
    function TestComponent() {
      hookResult = useBreadcrumbCollapse(sampleItems, 2); // Force collapse
      return <div>Test</div>;
    }
    
    renderBreadcrumb(<TestComponent />);
    
    expect(hookResult.isCollapsed).toBe(true);
    expect(hookResult.visibleItems.length).toBeLessThan(sampleItems.length);
    expect(hookResult.collapsedItems.length).toBeGreaterThan(0);
  });

  it("handles expand/collapse", () => {
    let hookResult: any;
    
    function TestComponent() {
      hookResult = useBreadcrumbCollapse(sampleItems, 2);
      return <div>Test</div>;
    }
    
    const { rerender } = renderBreadcrumb(<TestComponent />);
    
    // Test expand
    hookResult.expand();
    rerender(
      <ThemeProvider theme={testTheme as any}>
        <TestComponent />
      </ThemeProvider>
    );
    
    // Test collapse
    hookResult.collapse();
    rerender(
      <ThemeProvider theme={testTheme as any}>
        <TestComponent />
      </ThemeProvider>
    );
    
    expect(hookResult.collapse).toBeDefined();
    expect(hookResult.expand).toBeDefined();
  });
});
